title: mc_rtc – Humanoids 2022 Workshop
author: >-
  Pierre Gergondet, [AIST-CNRS JRL](https://unit.aist.go.jp/jrl-22022/index_en.html)<br/>
  Arnaud Tanguy, [CNRS-UM LIRMM](https://www.lirmm.fr/lirmm-en/)<br/>
  Fumio Kanehiro, [AIST-CNRS JRL](https://unit.aist.go.jp/jrl-22022/index_en.html)<br/>
  Abderrahmane Kheddar, [CNRS-UM LIRMM](https://www.lirmm.fr/lirmm-en/) and [AIST-CNRS JRL](https://unit.aist.go.jp/jrl-22022/index_en.html)
description: >- # this means to ignore newlines until "baseurl:"
  General information about the mc_rtc workshop at <a href="https://www.humanoids2022.org/">Humanoids 2022</a>
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

theme: minima

header_pages:
  - objectives.markdown
  - schedule.markdown
  - prepare.markdown

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
